### ISSUE TITLE
Implement Search Result Page (Frontend)

### ISSUE THREAD

**Issue by dev-harshdeep** [dev-harshdeep/Exam-Archive-x#11]
# Description:
## Feature Request
I propose the addition of a search result page in the frontend. This feature will allow users to search for specific content and receive relevant search results displayed on a dedicated page.

### Description
This feature focuses solely on the frontend part:

## Search Result Page:

+ Design a search result page that allows users to input search queries.
+ When a user performs a search, the page should display placeholder search results, simulating the behavior of a fully functional search feature.

**Comment by VivekSunori** [comment]
ok i will be working on that .
