### ISSUE TITLE
Implement Admin Question Paper Management Feature with Dynamic Selectors

### ISSUE THREAD

**Issue by dev-harshdeep** [dev-harshdeep/Exam-Archive-x#7]
# Description:
## Feature Request
I would like to propose the addition of a new feature that allows administrators to manage question papers, including the ability to add new question papers and edit their details. This feature should include dynamic selectors for subject name, course name, and subject code, ensuring that the options are updated based on the user's selections.

## Description
The goal of this feature is to streamline the process of adding and managing question papers, making it more efficient and user-friendly. Here are the key requirements:

## Dynamic Selectors:

When an admin selects a course name, the subject name selector should update to display only subjects related to the chosen course.
Similarly, when a subject code is selected, the course and semester selectors should update to show only the options that correspond to that subject code within the database.
## Add New Question Papers:

Admins should be able to upload and manage new question papers.
They should provide details such as the year, semester, subject, and any additional information relevant to the question paper.
Edit Question Paper Details:

### Admins should have the ability to edit the details of existing question papers and delete existing question papers.

**Comment by Gauravchandola2022** [comment]
Yes, I would like to work on this issue.
