### ISSUE TITLE
Implement Google Login for Admins and Secure User Authentication

### ISSUE THREAD

**Issue by dev-harshdeep** [dev-harshdeep/Exam-Archive-x#8]
# Description:
## Feature Request
I would like to propose the addition of a new feature that enables administrators to log in using their Google accounts. Furthermore, we need to implement secure user authentication to ensure that the admin page is only accessible to authenticated administrators.

### 1. Google Login for Admins:
Administrators should have the option to log in to our application using their Google accounts. This will simplify the login process and enhance security by leveraging Google's authentication system.

### 2. Secure User Authentication:
We need to implement a secure authentication system for administrators. This includes the following aspects:

#### Admin Userbase Table Schema:
Define the schema for the admin userbase table, including necessary fields such as username, email, password (hashed and salted), and any other relevant attributes. It's crucial to securely store admin user data.

#### Admin Page Access Control:
Ensure that only authenticated administrators can access the admin page. Unauthorized users or non-administrators should be redirected to the login page or denied access.

#### Session Management:
Implement secure session management to track and validate admin user sessions. This includes setting up secure session cookies and handling session expiration.

#### Security Best Practices:
Follow best practices for securing user authentication, such as password hashing, salted passwords, and protection against common vulnerabilities like SQL injection and Cross-Site Scripting (XSS).

**Comment by 02SHIVAM3** [comment]
I'd like to work on this issue
